name: CI Laravel Presentasi Fitur

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  galeri-feature:
    runs-on: ubuntu-latest
    name: ✅ Test Galeri Feature
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, bcmath
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Run Galeri Feature Test
        run: |
          php artisan test --filter GaleriTest

  agenda-feature:
    runs-on: ubuntu-latest
    name: ✅ Test Agenda Feature
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, xml, bcmath
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite

      - name: Run Agenda Feature Test
        run: |
          php artisan test --filter AgendaTest
